import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("provides a poetry interpretation workbench and per-scene image generation", async () => {
  const source = await readFile(new URL("./App.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("./styles.css", import.meta.url), "utf8");

  assert.match(source, /aria-label="打开诗词意境工作台"/);
  assert.match(source, /className="extension-rail"/);
  assert.match(source, /data-label="诗词意境"/);
  assert.match(source, /咸阳城东楼/);
  assert.match(source, /DEFAULT_POETRY_SCENES/);
  assert.match(source, /DEFAULT_POETRY_ANALYSIS/);
  assert.match(source, /已保存诗词/);
  assert.ok(source.includes("/api/poetry/projects"));
  assert.ok(source.includes("function applyPoetryProject(project: PoetryProject)"));
  assert.ok(source.includes("function savePoetryProject"));
  assert.match(source, /poetrySaveTimer\.current = window\.setTimeout/);
  assert.ok(source.includes("function startNewPoetryProject"));
  assert.match(source, /继续上次的分析、分镜和出图/);
  assert.ok(source.includes("/api/poetry/analyze"));
  assert.ok(source.includes("/api/poetry/interpret"));
  assert.match(source, /分析诗词意境/);
  assert.match(source, /生成分镜提示词/);
  assert.ok(source.includes("poetryAnalysis"));
  assert.ok(source.includes("analysis: poetryAnalysis"));
  assert.ok(source.includes("function handlePoemTextChange(value: string)"));
  assert.match(source, /意境分析/);
  assert.match(source, /整体解读/);
  assert.match(source, /时空背景/);
  assert.match(source, /情绪变化/);
  assert.match(source, /核心意象/);
  assert.match(source, /逐句理解/);
  assert.match(source, /画面段数/);
  assert.ok(source.includes('count === 6 ? "（默认）" : ""'));
  assert.match(source, /htmlFor="poetry-image-size">图片比例/);
  assert.ok(source.includes('id="poetry-image-size" value={size}'));
  assert.ok(source.includes("{option.name} · {option.detail}"));
  assert.ok(source.includes("JSON.stringify({ prompt: promptText, size,"));
  assert.match(source, /整体提示词补充/);
  assert.ok(source.includes("poetryPromptSupplement"));
  assert.ok(source.includes("[poetryStyleGuide, poetryPromptSupplement.trim(), scene.prompt]"));
  assert.ok(source.includes("function getPoetryCollectionName(poem: string)"));
  assert.ok(source.includes("function ensurePoetryCollection()"));
  assert.match(source, /图片合集：\{getPoetryCollectionName\(poemText\)\}/);
  assert.ok(source.includes("seriesId: collection.series.id"));
  assert.ok(source.includes("nodeId: node.id"));
  assert.match(source, /poetryScenes.map/);
  assert.ok(source.includes('aria-label={scene.title + "画面提示词"}'));
  assert.ok(source.includes("function generateOnePoetryScene(scene: PoetryScene)"));
  assert.ok(source.includes("generatePoetrySceneImageWithRetry"));
  assert.ok(source.includes("poetrySceneGenerationStates"));
  assert.match(source, /重新生成/);
  assert.ok(source.includes("function generateAllPoetryScenes()"));
  assert.ok(source.includes("/api/images/generate"));
  assert.match(source, /批量生成全部/);
  assert.match(source, /aria-label="诗词创作进度"/);
  assert.match(source, /意境分析/);
  assert.match(source, /分镜提示词/);
  assert.match(source, /图片生成/);
  assert.match(source, /aria-label="图片处理进度"/);
  assert.ok(source.includes("poetryImageProgress.completed"));
  assert.ok(source.includes('setPoetryProgress("正在生成第 " + scene.sceneOrder + " / " + poetryScenes.length'));
  assert.match(styles, /.poetry-dialog {/);
  assert.match(styles, /\.poetry-backdrop \{[^}]*place-items: stretch end/);
  assert.match(styles, /\.poetry-dialog \{[^}]*width: 70vw; height: 100dvh/);
  assert.match(styles, /@keyframes poetry-drawer-in \{ from \{ opacity: \.7; transform: translateX\(100%\)/);
  assert.ok(styles.includes(".poetry-scene-list { display: grid; grid-template-columns: repeat(2"));
  assert.match(styles, /\.poetry-analysis \{/);
  assert.match(styles, /\.poetry-line-reading \{/);
  assert.match(styles, /\.poetry-workflow-steps \{/);
  assert.match(styles, /\.poetry-image-progress-track \{/);
  assert.match(styles, /\.poetry-scene-generation-status \{/);
});

test("uses right-side drawers for the prompt library, series creation, and API settings", async () => {
  const styles = await readFile(new URL("./styles.css", import.meta.url), "utf8");

  assert.match(styles, /\.manager-backdrop \{ place-items: stretch end;/);
  assert.match(styles, /\.manager-dialog \{ width: 70vw; height: 100dvh;/);
  assert.match(styles, /\.api-settings-backdrop \{[^}]*place-items: stretch end;/);
  assert.match(styles, /\.api-settings-dialog \{[^}]*width: 70vw; height: 100dvh;/);
  assert.match(styles, /transform: translateX\(100%\)/);
});
